### ISSUE TITLE
Designation of the Joomla version

### ISSUE THREAD

**Issue by tecpromotion** [Valc/es-ES-core-language-packs#4]
Hi @Valc 
Eventually the last digit should be removed. The correct Joomla version is only 4.2.2

https://github.com/Valc/es-ES-core-language-packs/blob/561fc77a2b8825967b2d207287e2da6262b44f66/joomla_v4/pkg_es-ES.xml#L15

`Successfully installed the spanish language pack for Joomla! 4.2.2.2`

Joomla Version is: 4.2.2
`Successfully installed the spanish language pack for Joomla! 4.2.2`

**Comment by Valc** [comment]
@tecpromotion 
Right. This will be solved the next Joomla version.
Thank you.
